version: "3"

services:

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}"

  database:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  postgres_data:
